name: password_manager
description: "A secure Flutter-based password manager for Android"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2
  google_sign_in: ^5.4.4
  permission_handler: ^12.0.0+1
  local_auth: ^2.1.6
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  device_info_plus: ^10.1.0
  tutorial_coach_mark: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true

  assets:
    - icon.png
    - icons/password_generate_white.png
    - icons/password_generate_black.png
